### ISSUE TITLE
Reasoning for purple?

### ISSUE THREAD

**Issue by pdehaye** [bellingcat/sar-interference-tracker#1]
It says [here](https://www.bellingcat.com/resources/2022/02/11/radar-interference-tracker-a-new-open-source-tool-to-locate-active-military-radar-systems/) the full reasoning for the purple color would be on GitHub but I can't find it.

**Comment by MalikHadiUlHaq** [comment]
As per my understanding purple colour is depicted once you select the Daily layer from the Layer widget on the map. if u turn off the daily layer or change the opacity from the options it will disappear. hope it helps

**Comment by GalenReich** [comment]
I'm not sure of the justification for the purple colour - it may occur because of the `min` and `max` parameters for the different colour channels. The range is set differently for daily imagery.

https://github.com/bellingcat/sar-interference-tracker/blob/636514257b91afecb67e945705177177aba99ed4/RIT.js#L208-L226

**Comment by GalenReich** [comment]
Thank you for your patience in getting an answer! I've spoken to Ollie who developed the tracker, and have a bit more of an explanation (I'll update the README soon):

The monthly and yearly views display composites of multiple SAR images. These composites are made up of multiple SAR images, taken from Sentinel in both ascending and descending parts of its orbit. The red and blue channels are used to represent the SAR images taken in the ascending and descending parts of the orbit, respectively. When the satellite is ascending, the interference causes a red smear at one angle. When the satellite is descending, a blue smear is produced at a different angle. This channel mapping is the cause of the red and blue "x marks the spot" for points of interference.

That mapping is only possible for images that are a composite of multiple passes and you don't get that for the shorter time window of the daily imagery. Instead, the default colour scheme for the daily imagery uses the red and blue channels to represent the returns of different polarizations (VV & VH) of the Sentinal radar. The green channel is used to represent the look angle of the satellite, and so is roughly constant over each image (and at a fairly low level). This is why the Daily imagery looks very different and appears purple.

The choice of colour channel mapping is quite arbitrary, so there is nothing special about the colour purple, that's just what the default mapping results in.

If you are interested, you can see the mapping for the composite images (to RGB channels) being done here (note that `vhA_` refers to ascending data and `vhD_` refers to descending data):

https://github.com/bellingcat/sar-interference-tracker/blob/636514257b91afecb67e945705177177aba99ed4/RIT.js#L192-L198
