### ISSUE TITLE
Need for a license

### ISSUE THREAD

**Issue by wdturner** [bellingcat/sar-interference-tracker#2]
I read a really good article on this repository [https://www.bellingcat.com/resources/2022/02/11/radar-interference-tracker-a-new-open-source-tool-to-locate-active-military-radar-systems/](https://www.bellingcat.com/resources/2022/02/11/radar-interference-tracker-a-new-open-source-tool-to-locate-active-military-radar-systems/). It seemed to indicate that the code is open source, but when I got here there doesn't appear to be a license. For various legal issues, this can be a problem. Would it be possible to indicate in your repository the open source license this code is provided under? Github provides resources to help you select and apply a license.

**Comment by loganwilliams** [comment]
@oballinger What do you think about the MIT License? This matches our other projects.

**Comment by oballinger** [comment]
MIT License sounds good!
