### ISSUE TITLE
Guidance on identifying new sources

### ISSUE THREAD

**Issue by MalikHadiUlHaq** [bellingcat/sar-interference-tracker#6]
Hi
i have been trying to locate some known RFI sources falling under the range of this study . however, I have been unsuccessful in it as only example locations in the code are showing the RFI and not any new sources.
I can help in locating a lot of new sources with it

**Comment by GalenReich** [comment]
Hello, it's true that it's not always easy to find new sources. My guidance for an approach would be:

1. Select `Year` for `Display imagery aggregated by` - this gives you a broad view in time, if there is a particular period you are interested in, select a nearby date on the timeline
2. Zoom in to the area of interest and wait for the tiles to load
3. Pan around to try and spot examples of orange and blue interference pattern
4. Click on the location of interference and wait for the timeline to load
5. Select a region of high interference from the timeline and set the image aggregagtion to Day or Month.

[Here is an example from Sweden in 2017](https://ollielballinger.users.earthengine.app/view/bellingcat-radar-interference-tracker#lon=17.9472;lat=60.5893;zoom=11;date=2017-12-31T05%3A14%3A39;)

![image](https://github.com/bellingcat/sar-interference-tracker/assets/54807169/27ae19ad-62bf-4422-afd3-3da65479ad76)
